title:              Clean Blog
email:              cho4036@gmail.com
description:        A Blog Theme by Start Bootstrap
author:             Start Bootstrap
baseurl:            "" # "/startbootstrap-clean-blog-jekyll"
url:                "https://donggyu_cho.github.io"

# Social Profiles
twitter_username:   ""
github_username:    cho4036
facebook_username:  cho4036
instagram_username:  cho4036
linkedin_username: cho4036

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
